# Generated by Django 5.1.15 on 2026-06-03 10:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars/")),
                (
                    "bankroll",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="User's notional bankroll used to size recommended stakes (informational only).",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "kelly_fraction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Fraction of full Kelly to apply (e.g. 0.50 = half-Kelly, a common risk control).",
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "favorite_sport",
                    models.CharField(blank=True, default="basketball_nba", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
    ]
