# Generated by Django 5.1.15 on 2026-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("news", "News & Analysis"), ("guide", "Betting 101")],
                        db_index=True,
                        default="news",
                        max_length=10,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=400)),
                ("body", models.TextField(help_text="Markdown or HTML body.")),
                ("cover_image", models.ImageField(blank=True, upload_to="articles/")),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_published"], name="content_art_categor_bf2973_idx"
                    )
                ],
            },
        ),
    ]
