# Generated by Django 5.1.15 on 2026-06-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.CharField(
                blank=True, help_text="e.g. ESPN, for ingested news.", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Original article link, for ingested news."
            ),
        ),
    ]
