# Generated by Django 5.1.15 on 2026-06-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="The Odds API bookmaker key.", max_length=60, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
                ("region", models.CharField(default="us", max_length=10)),
                ("logo", models.ImageField(blank=True, upload_to="bookmakers/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
